# This is a basic workflow to help you get started with Actions
# handy notes on https://medium.com/mobile-development-group/github-actions-for-flutter-cf02923d7b5d
# https://github.com/marketplace/actions/dart-and-flutter-package-publisher
# https://github.com/subosito/flutter-action
  

name: Flutter CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        #flutter-version: '1.12.x' # you can use 1.12
        channel: 'stable' # optional, default to: 'stable', or can use 'dev', 'beta' or 'alpha'
    - run: flutter pub get
    - run: flutter analyze .
    #- run: flutter test
    #- run: flutter build apk
    - run: flutter build apk --target-platform android-arm64
     
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
